version: '3.8'

services:

  db:
    image: postgres:9.6.21
    environment:
      POSTGRES_DB: vite-kotlin-js-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 96f93e5d-7e9c-43d0-91a4-19679322ac21
    ports:
      - '25432:5432'
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: vite-kotlin-js-test # :@version@ - haven't figured out how to add yet
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'